### PR TITLE
add select box element and fix responsive

### PR DESCRIPTION
**Pull request by lamanhdai**
Hello I finished

### CODE REVIEW

**Comment by lamanhdai** [comment]
https://trello.com/c/rvLUDBNB/1-web-app-update-class-name-id

**Comment by lamanhdai** [comment]
and this ticket

**Comment by lamanhdai** [comment]
https://trello.com/c/bueZc91O/2-web-app-css-responsive-using-bootstrap

**Comment by nvminhtu** [comment]
I think you write so much, just only need one function or re-use a function - don't repeat your work.

**Pull request merged**
